---
title: "JMCNA 2021 - Data collection"
runtime : shiny
output: 
  flexdashboard::flex_dashboard:
    # theme: cerulean
    orientation: rows
    vertical_layout: scroll
    social : ["twitter","linkedin", "menu"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE)
library(flexdashboard)
library(lubridate)
library(shiny)
library(leaflet)
library(leaflet.extras)
library(readxl)
library(httr)
# library(dygraphs)
# library(xts)
# library(scales)
library(plotly)
library(DT)
# library(tmaptools)
# library(tmap)
library(sf)
library(tidyverse)
# library(writexl)
# library(knitr)
# library(RColorBrewer)
# library(viridisLite)


```


```{r setup kobo connection, warning=FALSE, include=FALSE}


source("Functions.R")
# url <-"https://kc.humanitarianresponse.info/api/v1/data.csv" ## Do not change this 
# kobo_user <-  "reachsomalia" ## kobo user 
# kobo_pw <- "ReachSom2020" ## kobo password 
# d_formlist_csv <- as.data.frame(kobohr_getforms_csv (url,kobo_user, kobo_pw)) ## Run this to get the list of deployed tool 
# form_id <-  "140646" ## Check the d_formlist_csv dataframe to get the correct form id
# dataurl<- paste0("https://kc.humanitarianresponse.info/api/v1/data/",form_id,".csv") ## Do not change this 
# 
# df <- download_data(dataurl,kobo_user,kobo_pw)
# colnames(df) <- gsub('^(?:[^/]*/)*(.*)', '\\1', colnames(df)) ## Removing group names from header

```

```{r Loading sampling files, message=FALSE, warning=FALSE, include=FALSE}

## data_all and data are test datasets, use the dataframe downloaded from the server (df).
## Make sure that the columns name are the same, if not I suggest that you change the naming in the dataset and keep
## the code as it is. An easy way around this is to use the rename function:
##################################################X
# df %>% 
#  rename(
#    new_name = old_name,
#    new_name2 = old_name2
#    )
##################################################X

data_all <- read.csv("input/rawdata.csv",stringsAsFactors = F) 
data <- head(data_all,9500)
target_region <- read.csv("input/target_region.csv",stringsAsFactors = F)
target_district <- read.csv("input/target_district.csv",stringsAsFactors = F)
target_settelment_hc <- read.csv("input/target_settelment_hc.csv",stringsAsFactors = F)

```

Main
=====================================

Row
-----------------------------------------------------------------------

### Conducted surveys
```{r}
valueBox(length(data$X_uuid),
         icon = "fa-file-text")
```

### National target

```{r}
rate <- computeSurveyRate(data,sum(target_district$target))
gauge(rate, min = 0, max = 100, symbol = '%', gaugeSectors(
  success = c(80, 100), warning = c(40, 79), danger = c(0, 39)
))
```


### district covered
```{r}
valueBox(length(unique(data$district)),
         icon = "fa-globe")
```


### Average survey duration
```{r}

valueBox(paste(computeDurationAverage(data)," Minutes"),
         icon = "fa-clock-o")
```



Row {data-heigth=650}
-----------------------------------------------------------------------


### Surveys submission overview - ALL

```{r}

p1 <- data %>% 
  group_by(region) %>% 
  summarise(count = n()) %>% 
  left_join(target_region %>% 
  select(region, total = target)) %>% 
  plot_ly( x = ~region,
           y = ~count,
           # color='blue',
           # text=c('A','B','C','D','B','C','D','A','A'),
           # textposition = 'auto',
           type='bar',
           name= "Conducted surveys"
           ) %>%
  add_trace(y = ~total, name = 'Remaining surveys') %>%
  layout(xaxis= list(title="Region"),
         yaxis= list(title="Surveys count"),
         barmode = 'stack')
p1
```

Row {data-heigth=650}
-----------------------------------------------------------------------


### Surveys submission overview - IDP

```{r}

p1 <- data %>% filter(idp_settlement == "yes") %>%
  group_by(region) %>% 
  summarise(count = n()) %>% 
  left_join(target_region %>% 
  select(region, total = idp)) %>% 
  plot_ly( x = ~region,
           y = ~count,
           # color='blue',
           # text=c('A','B','C','D','B','C','D','A','A'),
           # textposition = 'auto',
           type='bar',
           name= "Conducted surveys"
           ) %>%
  add_trace(y = ~total, name = 'Remaining surveys') %>%
  layout(xaxis= list(title="Region"),
         yaxis= list(title="Surveys count"),
         barmode = 'stack')
p1
```

### Surveys submission overview - Non IDP

```{r}

p1 <- data %>% filter(idp_settlement == "no")  %>%
  group_by(region) %>% 
  summarise(count = n()) %>% 
  left_join(target_region %>% 
  select(region, total = non_idp)) %>% 
  plot_ly( x = ~region,
           y = ~count,
           # color='blue',
           # text=c('A','B','C','D','B','C','D','A','A'),
           # textposition = 'auto',
           type='bar',
           name= "Conducted surveys"
           ) %>%
  add_trace(y = ~total, name = 'Remaining surveys') %>%
  layout(xaxis= list(title="Region"),
         yaxis= list(title="Surveys count"),
         barmode = 'stack')
p1
```

All {data-navmenu="Regions"}
=====================================

### Surveys submission overview - Region

```{r}

  datatable(
    data=data %>% group_by(region) %>% 
    summarise(Submission = n()) %>% 
    left_join(target_region %>% 
    select(region, Target = target)) %>% 
    mutate( Remaining = Target - Submission, 
           `Completion (%)` = round(Submission/Target * 100 , digits = 2)  ) ,
    filter = "top",
    options = list(pageLength=25),
    rownames = F
  
) %>%
      formatStyle("Completion (%)", backgroundColor = styleInterval(
      c(25,50,75), 
      c("red","orange","yellow","lightgreen")))
 
  


```

IDP {data-navmenu="Regions"}
=====================================

### Surveys submission overview - Region

```{r}

  datatable(
 
    data=data %>% filter(idp_settlement == "yes") %>% group_by(region) %>% 
    summarise(Submission = n()) %>% 
    left_join(target_region %>% 
    select(region, Target = idp)) %>% 
    mutate( Remaining = Target - Submission, 
           `Completion (%)` = round(Submission/Target * 100 , digits = 2)  ) ,
    filter = "top",
    options = list(pageLength=25),
    rownames = F
  
) %>%
      formatStyle("Completion (%)", backgroundColor = styleInterval(
      c(25,50,75), 
      c("red","orange","yellow","lightgreen")))
 
  


```


Non IDP {data-navmenu="Regions"}
=====================================

### Surveys submission overview - Region

```{r}

  datatable(
    data=data %>% filter(idp_settlement == "no") %>% group_by(region) %>% 
    summarise(Submission = n()) %>% 
    left_join(target_region %>% 
    select(region, Target = non_idp)) %>%  
    mutate( Remaining = Target - Submission, 
           `Completion (%)` = round(Submission/Target * 100 , digits = 2)  ) ,
    filter = "top",
    options = list(pageLength=25),
    rownames = F
  
) %>%
      formatStyle("Completion (%)", backgroundColor = styleInterval(
      c(25,50,75), 
      c("red","orange","yellow","lightgreen")))
 
  


```

All {data-navmenu="Districts"}
=====================================

Column {.sidebar}
-------------------------------------
```{r}
selectInput("RegionFilterA",
            "Regions:",
            choices = c("All",unique(data$region)))

```



Column {}
-------------------------------------
```{r}


DT::renderDataTable({
        if(input$RegionFilterA != "All"){
          datatable(
    data= data %>% filter(region == input$RegionFilterA )%>% group_by(district) %>% 
    summarise(Submission = n()) %>% 
    left_join(target_district %>% 
    select(district = District_xml, Target = target)) %>%  
    mutate( Remaining = Target - Submission, 
           `Completion (%)` = round(Submission/Target * 100 , digits = 2)  ) ,
    filter = "top",
    options = list(pageLength=25),
    rownames = F
  
) %>%
      formatStyle("Completion (%)", backgroundColor = styleInterval(
      c(25,50,75), 
      c("red","orange","yellow","lightgreen")))
        }
        else if(input$RegionFilterA == "All"){
          datatable(
    data= data %>% group_by(district) %>% 
    summarise(Submission = n()) %>% 
    left_join(target_district %>% 
    select(district = District_xml, Target = target)) %>%  
    mutate( Remaining = Target - Submission, 
           `Completion (%)` = round(Submission/Target * 100 , digits = 2)  ) ,
    filter = "top",
    options = list(pageLength=25),
    rownames = F
  
) %>%
      formatStyle("Completion (%)", backgroundColor = styleInterval(
      c(25,50,75), 
      c("red","orange","yellow","lightgreen")))
        }   
    }) 

  
  
```

IDP {data-navmenu="Districts"}
=====================================

Column {.sidebar}
-------------------------------------
```{r}
selectInput("RegionFilterB",
            "Regions:",
            choices = c("All",unique(data$region)))

```



Column {}
-------------------------------------
```{r}


DT::renderDataTable({
        if(input$RegionFilterB != "All"){
          datatable(
    data= data %>% filter(idp_settlement == "yes") %>% filter(region == input$RegionFilterB )%>% group_by(district) %>% 
    summarise(Submission = n()) %>% 
    left_join(target_district %>% 
    select(district = District_xml, Target = target)) %>%  
    mutate( Remaining = Target - Submission, 
           `Completion (%)` = round(Submission/Target * 100 , digits = 2)  ) ,
    filter = "top",
    options = list(pageLength=25),
    rownames = F
  
) %>%
      formatStyle("Completion (%)", backgroundColor = styleInterval(
      c(25,50,75), 
      c("red","orange","yellow","lightgreen")))
        }
        else if(input$RegionFilterB == "All"){
          datatable(
    data= data %>%  filter(idp_settlement == "yes") %>%  group_by(district) %>% 
    summarise(Submission = n()) %>% 
    left_join(target_district %>% 
    select(district = District_xml, Target = target)) %>%  
    mutate( Remaining = Target - Submission, 
           `Completion (%)` = round(Submission/Target * 100 , digits = 2)  ) ,
    filter = "top",
    options = list(pageLength=25),
    rownames = F
  
) %>%
      formatStyle("Completion (%)", backgroundColor = styleInterval(
      c(25,50,75), 
      c("red","orange","yellow","lightgreen")))
        }   
    }) 

  
  
```

Non IDP {data-navmenu="Districts"}
=====================================

Column {.sidebar}
-------------------------------------
```{r}
selectInput("RegionFilterC",
            "Regions:",
            choices = c("All",unique(data$region)))

```



Column {}
-------------------------------------
```{r}


DT::renderDataTable({
        if(input$RegionFilterC != "All"){
          datatable(
    data= data %>% filter(idp_settlement == "no") %>% filter(region == input$RegionFilterC )%>% group_by(district) %>% 
    summarise(Submission = n()) %>% 
    left_join(target_district %>% 
    select(district = District_xml, Target = target)) %>%  
    mutate( Remaining = Target - Submission, 
           `Completion (%)` = round(Submission/Target * 100 , digits = 2)  ) ,
    filter = "top",
    options = list(pageLength=25),
    rownames = F
  
) %>%
      formatStyle("Completion (%)", backgroundColor = styleInterval(
      c(25,50,75), 
      c("red","orange","yellow","lightgreen")))
        }
        else if(input$RegionFilterC == "All"){
          datatable(
    data= data %>%  filter(idp_settlement == "no") %>% group_by(district) %>% 
    summarise(Submission = n()) %>% 
    left_join(target_district %>% 
    select(district = District_xml, Target = target)) %>%  
    mutate( Remaining = Target - Submission, 
           `Completion (%)` = round(Submission/Target * 100 , digits = 2)  ) ,
    filter = "top",
    options = list(pageLength=25),
    rownames = F
  
) %>%
      formatStyle("Completion (%)", backgroundColor = styleInterval(
      c(25,50,75), 
      c("red","orange","yellow","lightgreen")))
        }   
    }) 

  
  
```

NC {data-navmenu="Settlements"}
=====================================

Column {.sidebar}
-------------------------------------
```{r}



selectInput("DistrictFilter",
            "District:",
            choices = c(unique(data$district)))

```


Column {}
-------------------------------------
```{r}



DT::renderDataTable({
     
          datatable(
    data= data %>% filter(district == input$DistrictFilter )%>% group_by(settlement) %>% 
    summarise(Submission = n()) %>% 
    left_join(target_settelment_hc %>% 
    select(settlement = P_CODE, Target = target)) %>%  
    mutate( Remaining = Target - Submission, 
           `Completion (%)` = round(Submission/Target * 100 , digits = 2)  ) ,
    filter = "top",
    options = list(pageLength=25),
    rownames = F
  
) %>%
      formatStyle("Completion (%)", backgroundColor = styleInterval(
      c(25,50,75), 
      c("red","orange","yellow","lightgreen")))
        
  
  })

  
  
```


Coverage map {}
=====================================

```{r include=FALSE}
#Load shapefile
base_map <- st_read("input/som-administrative-divisions-shapefiles/Som_Admbnda_Adm2_UNDP.shp")

#Load shapefile

base_map <- base_map %>% select(Shape_Leng, Shape_Area, admin2Pcod, admin2Name, geometry)
target_district <-read.csv("input/target_district.csv",stringsAsFactors = F)
base_map <- left_join(base_map, target_district)
data_all <- read.csv("input/rawdata.csv",stringsAsFactors = F) 
data <- data_all
# data <- head(data_all,1500)

data_summary <- data %>%  group_by(District_xml=district) %>% 
    summarise(conducted = n()) 

district_to_exclude <- c("Adan Yabaal", "Badhaadhe", "Baraawe", "Bu'aale", "Bulo Burto", "Cadale", "Caluula", "Ceel Buur", "Ceel Dheer", "Jalalaqsi", "Jamaame", "Kurtunwaarey", "Qandala", "Qansax Dheere", "Rab Dhuure", "Saakow", "Sablaale", "Tayeeglow", "Xarardheere")


# base_map <- base_map %>% filter(admin2Name %in% district_to_exclude)


base_map <- left_join(base_map, data_summary)

base_map$percent_quota_fulfilment <- round((base_map$conducted / base_map$target)*100 , digit = 2 )

# base_map %>% filter(is.na(District_xml)) %>% select(admin2Name,admin2Pcod,District,District_xml) %>% View()

base_map <- base_map %>% mutate(
  percent_quota_fulfilment = ifelse(is.na(percent_quota_fulfilment),500,percent_quota_fulfilment)
)
#Load data monitoring sheet



```


Column {.sidebar data-width=200}
-------------------------------------

```{r}
minvalue3 <- floor(min(base_map$percent_quota_fulfilment, na.rm = TRUE))
maxvalue3 <- ceiling(max(base_map$percent_quota_fulfilment, na.rm = TRUE))

sliderInput("rangevalues3",
  label = "Percentage of quota fulfilment per stratum:",
  min = minvalue3, max = maxvalue3,
  value = c(minvalue3, maxvalue3)
)



```


  
  
Column {data-width=400}
-------------------------------------

```{r}

pal3 <- colorBin(
  palette = c("red","yellow", "springgreen3","purple"), domain = base_map$percent_quota_fulfilment,
  bins = c(0,60,100,500,Inf)
)

labels <- c("0-59", "60-99", ">100","Non covered")

base_map$labels3 <- paste0(
  "<strong> Locality (EN): </strong> ",
  base_map$admin2Name , "<br/> ",
  "<strong> Percent quota fulfilment: </strong> ",
  base_map$percent_quota_fulfilment, "<br/> "

) %>%
  lapply(htmltools::HTML)

mapFiltered3 <- reactive({
  map_filter <- which(base_map$percent_quota_fulfilment >= input$rangevalues3[1] &
                        base_map$percent_quota_fulfilment <= input$rangevalues3[2] )
    base_map[map_filter, ]
})

renderLeaflet({
  if (nrow(mapFiltered3 ()) == 0) {
    return(NULL)
  }

  leaflet(mapFiltered3 ()) %>%
    addTiles() %>%
    setView(lng = 46.2176, lat = 9.5000, zoom = 5) %>%
    addPolygons(
      fillColor = ~ pal3(percent_quota_fulfilment),
      color = "white",
      weight = 2,
      fillOpacity = 1,
      label = ~labels3,
      highlight = highlightOptions(
        color = "black",
        bringToFront = TRUE
      )
    ) %>%
    leaflet::addLegend(
      pal = pal3, values = ~ percent_quota_fulfilment,
      opacity = 0.8, 
      title = "Percent quota fulfilment per stratum (accepted surveys divided by quota)",
      labFormat = function(type, cuts, p) { paste0(labels)}
    )
})

```



